#!/bin/bash

alias ll='ls -Fl'
alias la='ls -Fal'
alias l='ll'

alias g='git'
alias gs='git status'
alias gd='git diff'
alias ga='git add'
alias gc='git commit'
alias gl="git log --oneline --graph --all --pretty=format:'%Cred%h %C(reset)%C(green)(%cr)%C(reset) %C(bold blue)%an%C(reset)%C(red)%d%C(reset) %s'"

